
import type { Difficulty, DifficultySetting, Theme, ThemeConfig, Language, Translations } from './types';

export const DIFFICULTY_SETTINGS: Record<Difficulty, DifficultySetting> = {
  easy:   { minDigits: 2, maxDigits: 2, time: 12 },
  medium: { minDigits: 3, maxDigits: 3, time: 10 },
  hard:   { minDigits: 4, maxDigits: 4, time: 8 },
  guru:   { minDigits: 4, maxDigits: 8, dynamicTime: { base: 2, perDigit: 1.5 } }
};

export const THEMES: Record<Theme, ThemeConfig> = {
  nebula: {
    gradient: 'from-gray-900 via-purple-900 to-gray-900',
    panelBg: 'bg-black/40 backdrop-blur-xl border border-purple-500/30',
    textColor: 'text-purple-100',
    accentColor: 'text-purple-400',
    buttonBg: 'bg-purple-600',
    buttonHoverBg: 'hover:bg-purple-500',
    inputBg: 'bg-gray-900/50',
    inputBorder: 'border-purple-400',
    focusRing: 'focus:ring-purple-500'
  },
  sunset: {
    gradient: 'from-slate-900 via-orange-900 to-slate-900',
    panelBg: 'bg-black/40 backdrop-blur-xl border border-orange-500/30',
    textColor: 'text-orange-100',
    accentColor: 'text-orange-400',
    buttonBg: 'bg-orange-600',
    buttonHoverBg: 'hover:bg-orange-500',
    inputBg: 'bg-gray-900/50',
    inputBorder: 'border-orange-400',
    focusRing: 'focus:ring-orange-500'
  },
  forest: {
    gradient: 'from-gray-900 via-green-900 to-gray-900',
    panelBg: 'bg-black/40 backdrop-blur-xl border border-green-500/30',
    textColor: 'text-green-100',
    accentColor: 'text-green-400',
    buttonBg: 'bg-green-600',
    buttonHoverBg: 'hover:bg-green-500',
    inputBg: 'bg-gray-900/50',
    inputBorder: 'border-green-400',
    focusRing: 'focus:ring-green-500'
  },
  ocean: {
    gradient: 'from-slate-900 via-blue-900 to-slate-900',
    panelBg: 'bg-black/40 backdrop-blur-xl border border-blue-500/30',
    textColor: 'text-blue-100',
    accentColor: 'text-blue-400',
    buttonBg: 'bg-blue-600',
    buttonHoverBg: 'hover:bg-blue-500',
    inputBg: 'bg-gray-900/50',
    inputBorder: 'border-blue-400',
    focusRing: 'focus:ring-blue-500'
  }
};

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    title: 'Binokub Calculator',
    description: 'Calculate the "Base" of the number below by repeatedly summing its digits until you get a single-digit number (1-9). Enter your answer before time runs out!',
    start_game: 'Start Game',
    game_over: 'Game Over',
    score: 'Score',
    high_score: 'High Score',
    play_again: 'Play Again',
    your_answer: 'Your Answer...',
    select_theme: 'Select Theme',
    select_language: 'Select Language',
    select_difficulty: 'Select Difficulty',
    difficulty_easy: 'Easy',
    difficulty_medium: 'Medium',
    difficulty_hard: 'Hard',
    difficulty_guru: 'Guru',
    level: 'Level',
    time: 'Time',
    share_score: 'Share Score',
    share_text: 'I scored {score}/10 in the Binokub Calculator! Can you beat it?',
    copied_to_clipboard: 'Copied!',
    how_to_play: 'How to Play',
    how_to_play_title: 'How to Play',
    how_to_play_goal: 'Goal: Find the "Base" of the number.',
    how_to_play_calc: 'Calculation: Sum the digits. If the result has more than one digit, sum again until you get a single digit (1-9).',
    how_to_play_example_title: 'Example:',
    how_to_play_example_text: 'For 78 → 7 + 8 = 15 → 1 + 5 = 6. The Base is 6.',
    how_to_play_game: 'Game: Enter the Base before time runs out. Get 10 correct answers to win!',
    got_it: 'Got It',
  },
  fr: {
    title: 'Calculateur Binokub',
    description: 'Calculez la "Base" du nombre ci-dessous en additionnant ses chiffres de manière répétée jusqu\'à obtenir un seul chiffre (1-9). Entrez votre réponse avant la fin du temps imparti !',
    start_game: 'Commencer',
    game_over: 'Partie Terminée',
    score: 'Score',
    high_score: 'Meilleur Score',
    play_again: 'Rejouer',
    your_answer: 'Votre Réponse...',
    select_theme: 'Choisir un Thème',
    select_language: 'Choisir la Langue',
    select_difficulty: 'Choisir la Difficulté',
    difficulty_easy: 'Faible',
    difficulty_medium: 'Moyen',
    difficulty_hard: 'Fort',
    difficulty_guru: 'Guru',
    level: 'Niveau',
    time: 'Temps',
    share_score: 'Partager le Score',
    share_text: "J'ai eu un score de {score}/10 au Calculateur Binokub ! Pouvez-vous me battre ?",
    copied_to_clipboard: 'Copié !',
    how_to_play: 'Comment Jouer',
    how_to_play_title: 'Comment Jouer',
    how_to_play_goal: 'Objectif : Trouver la "Base" du nombre.',
    how_to_play_calc: "Calcul : Additionnez les chiffres. Si le résultat a plus d'un chiffre, additionnez à nouveau jusqu'à obtenir un seul chiffre (1-9).",
    how_to_play_example_title: 'Exemple :',
    how_to_play_example_text: 'Pour 78 → 7 + 8 = 15 → 1 + 5 = 6. La Base est 6.',
    how_to_play_game: 'Jeu : Entrez la Base avant la fin du temps. Obtenez 10 bonnes réponses pour gagner !',
    got_it: 'Compris',
  },
  es: {
    title: 'Calculadora Binokub',
    description: 'Calcula la "Base" del número de abajo sumando repetidamente sus dígitos hasta obtener un número de un solo dígito (1-9). ¡Ingresa tu respuesta antes de que se acabe el tiempo!',
    start_game: 'Empezar Juego',
    game_over: 'Juego Terminado',
    score: 'Puntuación',
    high_score: 'Puntuación Máxima',
    play_again: 'Jugar de Nuevo',
    your_answer: 'Tu Respuesta...',
    select_theme: 'Seleccionar Tema',
    select_language: 'Seleccionar Idioma',
    select_difficulty: 'Seleccionar Dificultad',
    difficulty_easy: 'Fácil',
    difficulty_medium: 'Medio',
    difficulty_hard: 'Difícil',
    difficulty_guru: 'Gurú',
    level: 'Nivel',
    time: 'Tiempo',
    share_score: 'Compartir Puntuación',
    share_text: '¡He conseguido {score}/10 en la Calculadora Binokub! ¿Puedes superarlo?',
    copied_to_clipboard: '¡Copiado!',
    how_to_play: 'Cómo Jugar',
    how_to_play_title: 'Cómo Jugar',
    how_to_play_goal: 'Objetivo: Encuentra la "Base" del número.',
    how_to_play_calc: 'Cálculo: Suma los dígitos. Si el resultado tiene más de un dígito, vuelve a sumar hasta obtener un solo dígito (1-9).',
    how_to_play_example_title: 'Ejemplo:',
    how_to_play_example_text: 'Para 78 → 7 + 8 = 15 → 1 + 5 = 6. La Base es 6.',
    how_to_play_game: 'Juego: Introduce la Base antes de que se acabe el tiempo. ¡Consigue 10 respuestas correctas para ganar!',
    got_it: 'Entendido',
  },
  de: {
    title: 'Binokub-Rechner',
    description: 'Berechnen Sie die "Basis" der folgenden Zahl, indem Sie ihre Ziffern wiederholt addieren, bis Sie eine einstellige Zahl (1-9) erhalten. Geben Sie Ihre Antwort ein, bevor die Zeit abläuft!',
    start_game: 'Spiel Starten',
    game_over: 'Spiel Vorbei',
    score: 'Punktzahl',
    high_score: 'Höchstpunktzahl',
    play_again: 'Nochmal Spielen',
    your_answer: 'Deine Antwort...',
    select_theme: 'Thema Auswählen',
    select_language: 'Sprache Auswählen',
    select_difficulty: 'Schwierigkeit Wählen',
    difficulty_easy: 'Leicht',
    difficulty_medium: 'Mittel',
    difficulty_hard: 'Schwer',
    difficulty_guru: 'Guru',
    level: 'Level',
    time: 'Zeit',
    share_score: 'Ergebnis Teilen',
    share_text: 'Ich habe {score}/10 im Binokub-Rechner erreicht! Kannst du das übertreffen?',
    copied_to_clipboard: 'Kopiert!',
    how_to_play: 'Spielanleitung',
    how_to_play_title: 'Spielanleitung',
    how_to_play_goal: 'Ziel: Finde die "Basis" der Zahl.',
    how_to_play_calc: 'Berechnung: Addiere die Ziffern. Wenn das Ergebnis mehr als eine Ziffer hat, addiere erneut, bis du eine einzelne Ziffer (1-9) erhältst.',
    how_to_play_example_title: 'Beispiel:',
    how_to_play_example_text: 'Für 78 → 7 + 8 = 15 → 1 + 5 = 6. Die Basis ist 6.',
    how_to_play_game: 'Spiel: Gib die Basis ein, bevor die Zeit abläuft. Beantworte 10 Fragen richtig, um zu gewinnen!',
    got_it: 'Verstanden',
  },
};